name: WELCOME DIVINE INTELLIGENCE
favicon: null
layout_spectrum: 0.15023273159749806
typography_spectrum: 0.2397608240135014
title: WELCOME DIVINE INTELLIGENCE - A philosophical research blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0c0b'
    - '#594433'
    - '#ffffff'
    - '#bd532c'
    - '#ee7139'
  brandStrength: 0.9222695315256715
  lightness: 0.45931513141840696
  saturation: 0.1339303650893271
  rhythmicContrast: 0.36502608144655824
purpose: []
